### ISSUE TITLE
Debian pkg broken!

### ISSUE THREAD

**Issue by MrFlyingToasterman** [hawkeye116477/waterfox-deb#12]
Im the Administrator of a small privacy orientated network.
We are currently using Waterfox as default browser.

We can't upgrade any machine! All of them are running Debian GNU/Linux 9
4 Computers tested so far.

My `uname -a`
`Linux RichterWS4 4.9.0-7-amd64 #1 SMP Debian 4.9.110-1 (2018-07-05) x86_64 GNU/Linux`

This is what i get when im trying to install waterfox:

```
root@RichterWS1 ~# apt install waterfox
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Einige Pakete konnten nicht installiert werden. Das kann bedeuten, dass
Sie eine unmögliche Situation angefordert haben oder, wenn Sie die
Unstable-Distribution verwenden, dass einige erforderliche Pakete noch
nicht erstellt wurden oder Incoming noch nicht verlassen haben.
Die folgenden Informationen helfen Ihnen vielleicht, die Situation zu lösen:

Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 waterfox : Hängt ab von: libc6 (>= 2.27) aber 2.24-11+deb9u3 soll installiert werden
            Hängt ab von: libfontconfig1 (>= 2.12.6) aber 2.11.0-6.7+b1 soll installiert werden
            Empfiehlt: waterfox-kde soll aber nicht installiert werden
E: Probleme können nicht korrigiert werden, Sie haben zurückgehaltene defekte Pakete.
```
It says: **unmet dependencies**.
It wants to install **libc6** version _2.24-11+deb9u3_ but it needs _2.27_ and
it wants to install **libfontconfig1** version _2.11.0-6.7+b1_ but it needs  _2.12.6_

The new repo was correctly installed and signed by the release key.
The old repo was removed.

The german locale is working fine:
```
root@RichterWS1 ~# apt install waterfox-locale-de
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Die folgenden NEUEN Pakete werden installiert:
  waterfox-locale-de
0 aktualisiert, 1 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Es müssen 466 kB an Archiven heruntergeladen werden.
Nach dieser Operation werden 552 kB Plattenplatz zusätzlich benutzt.
Holen:1 http://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/Debian_Testing  waterfox-locale-de 56.2.4-0 [466 kB]
Es wurden 466 kB in 0 s geholt (883 kB/s). 
Vormals nicht ausgewähltes Paket waterfox-locale-de wird gewählt.
(Lese Datenbank ... 185367 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../waterfox-locale-de_56.2.4-0_amd64.deb ...
Entpacken von waterfox-locale-de (56.2.4-0) ...
waterfox-locale-de (56.2.4-0) wird eingerichtet ...
```

Please fix that problem as soon as possible.

**Comment by MrFlyingToasterman** [comment]
@hawkeye116477 Thank you for your quick replay!

But this seems not to work either:
```
root@RichterWS1 ~# apt install waterfox
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Einige Pakete konnten nicht installiert werden. Das kann bedeuten, dass
Sie eine unmögliche Situation angefordert haben oder, wenn Sie die
Unstable-Distribution verwenden, dass einige erforderliche Pakete noch
nicht erstellt wurden oder Incoming noch nicht verlassen haben.
Die folgenden Informationen helfen Ihnen vielleicht, die Situation zu lösen:

Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 waterfox : Hängt ab von: libfontconfig1 (>= 2.11.94) aber 2.11.0-6.7+b1 soll installiert werden
            Empfiehlt: waterfox-kde soll aber nicht installiert werden
E: Probleme können nicht korrigiert werden, Sie haben zurückgehaltene defekte Pakete.
```

Now there is only a version problem with **libfontconfig1**

Here's more information

```
cat /etc/apt/sources.list
[...]
#Waterfox
deb http://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/xUbuntu_16.04/ /
```

```
root@RichterWS1 ~# uname -a
Linux RichterWS1 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64 GNU/Linux
```

**Comment by MrFlyingToasterman** [comment]
I found a dirty way to get Waterfox running on my system.

I've downloaded the Waterfox pkg via apt from the Ubuntu 16.04 repo
```
root@RichterWS1 ~# apt download waterfox
Holen:1 http://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/xUbuntu_16.04  waterfox 56.2.4-0 [41,3 MB]
Es wurden 41,3 MB in 29 s geholt (1.418 kB/s).   
```                                                 
Now, i got a local _.deb_                  
```
root@RichterWS1 ~# ll
-rw-r--r-- 1 root root  40M Okt 15 16:35 waterfox_56.2.4-0_amd64.deb
                               
```                                  
Then i used **dpkg** to install the package:
```
root@RichterWS1 ~# dpkg -i waterfox_56.2.4-0_amd64.deb 
Vormals nicht ausgewähltes Paket waterfox wird gewählt.
(Lese Datenbank ... 185919 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von waterfox_56.2.4-0_amd64.deb ...
Entpacken von waterfox (56.2.4-0) ...
dpkg: Abhängigkeitsprobleme verhindern Konfiguration von waterfox:
 waterfox hängt ab von libfontconfig1 (>= 2.11.94); aber:
  Version von libfontconfig1:amd64 auf dem System ist 2.11.0-6.7+b1.

dpkg: Fehler beim Bearbeiten des Paketes waterfox (--install):
 Abhängigkeitsprobleme - verbleibt unkonfiguriert
Trigger für man-db (2.7.6.1-2) werden verarbeitet ...
Trigger für gnome-menus (3.13.3-9) werden verarbeitet ...
Trigger für desktop-file-utils (0.23-1) werden verarbeitet ...
Trigger für mime-support (3.60) werden verarbeitet ...
Fehler traten auf beim Bearbeiten von:
 waterfox
```
It drops an error, but it's running.
I guess this is a very ugly way to force the installation.

Another problem is, now i can't upgrade my system anymore:
```
root@RichterWS1 ~# apt full-upgrade
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Probieren Sie »apt --fix-broken install«, um dies zu korrigieren.
Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 waterfox : Hängt ab von: libfontconfig1 (>= 2.11.94) aber 2.11.0-6.7+b1 ist installiert
            Empfiehlt: waterfox-kde ist aber nicht installiert
E: Unerfüllte Abhängigkeiten. Versuchen Sie »apt --fix-broken install« ohne Angabe eines Pakets (oder geben Sie eine Lösung an).
```
It says: **unmet dependencies**.

The package needs **libfontconfig1** version **2.11.94** but installs **2.11.0-6.7+b1**!

Further, when i try to `--fix-broken`, apt want to remove the Waterfox package:
```
root@RichterWS1 ~# apt --fix-broken install
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Abhängigkeiten werden korrigiert ... Fertig
Die folgenden Pakete werden ENTFERNT:
  waterfox
0 aktualisiert, 0 neu installiert, 1 zu entfernen und 0 nicht aktualisiert.
1 nicht vollständig installiert oder entfernt.
Nach dieser Operation werden 162 MB Plattenplatz freigegeben.
Möchten Sie fortfahren? [J/n] n
Abbruch.
```


Can you please fix the unmet dependencies?

**Comment by hawkeye116477** [comment]
I see what I can do. I'll reply later when it will be ready.

**Comment by hawkeye116477** [comment]
Temporary solution for now, download https://www105.zippyshare.com/v/zGfkPdZx/file.html and install it. It's not compiled by me, it's from officially compiled package, so should be working.

**Comment by MrFlyingToasterman** [comment]
@hawkeye116477 
I don't trust any zippyshare binary, that not even you compiled.

This is not an acceptable solution!
Not even temporary :(

Please fix the unmet dependencies.

**Comment by hawkeye116477** [comment]
@MrFlyingToasterman I mean I created it from package from https://www.waterfoxproject.org, so MrAlex94 compiled it.

**Comment by MrFlyingToasterman** [comment]
@hawkeye116477 

I'm sorry, i don't trust zippyshare. 
Please let me know when the patch is done.

I use your Repo for Waterfox in the office and at home.
Even my family is using it. Please fix this issue as soon as possible.

**Comment by hawkeye116477** [comment]
@MrFlyingToasterman Ok, I uploaded it also to Google Drive `https://drive.google.com/file/d/1wC7-lkdLVCEcqRRxFYGmuEhNWndpgPPL/view?usp=sharing`
Anyway, I'll try to fix that, but cuz Debian 9 hasn't Cargo, that won't be that easy, so I'll probably must build Cargo for Debian on my repo or just try to build Waterfox for Trusty, which has libfontconfig1 version 2.11.0-0, but for Trusty I'll must disable stylo for now, cuz it's don't want to build stylo, displays error unfortunately, I don't know why. But as Trusty has libfontconfig1 in that version, then Waterfox for Trusty (U14.04), should work. 
Version for Trusty should be ready in about 1 hour if it compiles successfully.

**Comment by MrFlyingToasterman** [comment]
@hawkeye116477 The old Repo worked perfectly fine.
I run into this trouble since you changed your Repo.

And why do you need cargo ?
This is a simple packaging issue. Just a version missmatch.
As far as i can see it...

I'll try the 14.04 version, as soon as it's ready!
Of course you get a feedback after that.

**Comment by hawkeye116477** [comment]
@MrFlyingToasterman It was because I previously didn't compiled waterfox, I made waterfox.deb from tarball with binary from waterfoxproject.org, using not cool method, cuz depends was entered by manual. Now it is compiled and depends are automatically detected just like other maintainers do.
Cargo is needed to compile Waterfox.

**Comment by MrFlyingToasterman** [comment]
@hawkeye116477 Ah, i see. So it is possible that you add a **waterfox-src** to your Repo ?
You can ship it with **cargo** as dependency. Maybe with a little installscript that compiles Waterfox and installs it ?

This would be a great temporary solution until the Debian candidate is working.

**Comment by MrFlyingToasterman** [comment]
@hawkeye116477 Waterfox compile finished but the Resource is no longer available!
https://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/xUbuntu_14.04

**Comment by hawkeye116477** [comment]
@MrFlyingToasterman It's just not available on apt repo yet, I don't know why, but sometimes that happens and appears after some time. But for now, you can just download it from <https://build.opensuse.org/package/binary/download/home:hawkeye116477:waterfox/waterfox/xUbuntu_14.04/x86_64/waterfox_56.2.4-0_amd64.deb>.

**Comment by MrFlyingToasterman** [comment]
Well, im not interested in temporary solutions. I decided to use the evil Mozilla Fox until you fixed that. I hope it runs soon like it used to be. Please consider making a official Debian 9 candidate!

**Otherwise Waterfox & especially your Repo is not longer usable for me or my clients!**

**Comment by hawkeye116477** [comment]
@MrFlyingToasterman Ok. Sorry, I forgot that previously unchecked publish flag for Trusty, but I checked it now and it's on repo.

**Comment by MrFlyingToasterman** [comment]
@hawkeye116477 this seems to work. But how long will that last ?
I would appreciate if you fix the Debian 9 repo: https://build.opensuse.org/package/binaries/home:hawkeye116477:waterfox/waterfox/Debian_9.0
 **To make sure, that this will never happen again!**

But i can accept it as a temporary Solution.

Please let me know if the right repo is working again!

**Comment by Kyugestu** [comment]
To solve this problem, I would also be very happy. I hope to be able to count on a happy customer soon. Thank you and good luck. = D The guy with the weird name.

**Comment by hawkeye116477** [comment]
@MrFlyingToasterman As I previously talked, I'll se if I can do something, but will be easier if you maybe wrote some request to Debian Team to provide Cargo in Debian 9 :smile:.

**Comment by MrFlyingToasterman** [comment]
@hawkeye116477 you can ship it with as dependency in a working Debian 9 candidate.

**Comment by hawkeye116477** [comment]
Dependency? Cargo is only needed for compiling, so it's only needed for me :smile: It's build-dependency.

**Comment by MrFlyingToasterman** [comment]
@hawkeye116477 since i've updated my machines, Waterfox is running terrible!
Half of the websites needed by our employees, crashes! 
For example, we are using DuckDuckGo as default search engine.
Everytime we search for a location and DuckDuckGo brings up a tiny Map, the Tab dies instantly.
Google Maps dies directly too.
But OpenStreetMap & Bing Maps are working strangely.

Maybe this is a compiling issue ?
Im using Waterfox 56.2.4 on Debian 9.

On my Arch Linux setup im using 56.2.3 and its running perfectly fine.
Maybe its a Waterfox bug?
But im pretty sure its a bug in your Version.

Pls fix this as soon as possible!

**Comment by MrFlyingToasterman** [comment]
This is what i get when im searching for the location `Roller Ratingen` with DuckDuckGo
```
testumgebung@RichterWS21 ~> waterfox
terminate called after throwing an instance of 'std::regex_error'
what(): regex_error
Redirecting call to abort() to mozalloc_abort

[Parent 8550] WARNING: pipe error (41): Die Verbindung wurde vom Kommunikationspartner zurückgesetzt: file /usr/src/packages/BUILD/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
[Parent 8550] WARNING: pipe error (36): Die Verbindung wurde vom Kommunikationspartner zurückgesetzt: file /usr/src/packages/BUILD/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353

###!!! [Parent][MessageChannel] Error: (msgtype=0x420017,name=PHttpChannel::Msg_DeleteSelf) Channel error: cannot send/recv


###!!! [Parent][MessageChannel] Error: (msgtype=0x420017,name=PHttpChannel::Msg_DeleteSelf) Channel error: cannot send/recv


###!!! [Parent][MessageChannel] Error: (msgtype=0x420017,name=PHttpChannel::Msg_DeleteSelf) Channel error: cannot send/recv


###!!! [Parent][MessageChannel] Error: (msgtype=0x150079,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv
```
It says in german: **The connection was reset by the communication partner**
And this is why i want a clean solution!

**Comment by MrFlyingToasterman** [comment]
Here is the complete log, i get when im trying to open `maps.google.com` with **Waterfox 56.2.4** on Debian 9 from the Repo `http://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/xUbuntu_14.04/`:

```
dmusiolik@RichterWS22 ~> waterfox 
1540370719301	addons.webextension.chrome-gnome-shell@gnome.org	WARN	Please specify whether you want browser_style or not in your browser_action options.
console.error: self-destructing-cookies: 
  localstorage: 
  securityManager.getNoAppCodebasePrincipal is not a function
console.error: self-destructing-cookies: 
  localstorage: 
  securityManager.getNoAppCodebasePrincipal is not a function
console.error: self-destructing-cookies: 
  localstorage: 
  securityManager.getNoAppCodebasePrincipal is not a function
ATTENTION: default value of option force_s3tc_enable overridden by environment.
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error
Redirecting call to abort() to mozalloc_abort


###!!! [Parent][MessageChannel] Error: (msgtype=0x150064,name=PBrowser::Msg_StopIMEStateManagement) Channel error: cannot send/recv


###!!! [Parent][MessageChannel] Error: (msgtype=0x24004F,name=PContent::Msg_Deactivate) Channel error: cannot send/recv


###!!! [Parent][RunMessage] Error: Channel error: cannot send/recv


###!!! [Parent][RunMessage] Error: Channel error: cannot send/recv


###!!! [Parent][RunMessage] Error: Channel error: cannot send/recv


###!!! [Parent][RunMessage] Error: Channel error: cannot send/recv


###!!! [Parent][RunMessage] Error: Channel error: cannot send/recv


###!!! [Parent][RunMessage] Error: Channel error: cannot send/recv


###!!! [Parent][RunMessage] Error: Channel error: cannot send/recv


###!!! [Parent][RunMessage] Error: Channel error: cannot send/recv


###!!! [Parent][RunMessage] Error: Channel error: cannot send/recv


###!!! [Parent][RunMessage] Error: Channel error: cannot send/recv


###!!! [Parent][RunMessage] Error: Channel error: cannot send/recv


###!!! [Parent][RunMessage] Error: Channel error: cannot send/recv


###!!! [Parent][RunMessage] Error: Channel error: cannot send/recv


###!!! [Parent][RunMessage] Error: Channel error: cannot send/recv


###!!! [Parent][RunMessage] Error: Channel error: cannot send/recv


###!!! [Parent][RunMessage] Error: Channel error: cannot send/recv


###!!! [Parent][RunMessage] Error: Channel error: cannot send/recv


###!!! [Parent][RunMessage] Error: Channel error: cannot send/recv


###!!! [Parent][MessageChannel] Error: (msgtype=0x420017,name=PHttpChannel::Msg_DeleteSelf) Channel error: cannot send/recv


###!!! [Parent][MessageChannel] Error: (msgtype=0x150079,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv

^C⏎                                                                                                                                                                                                                 

dmusiolik@RichterWS22 ~> 
```
